/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CoffeeShop } from "./CoffeeShop";
import { CoffeeShopCountArgs } from "./CoffeeShopCountArgs";
import { CoffeeShopFindManyArgs } from "./CoffeeShopFindManyArgs";
import { CoffeeShopFindUniqueArgs } from "./CoffeeShopFindUniqueArgs";
import { DeleteCoffeeShopArgs } from "./DeleteCoffeeShopArgs";
import { CoffeeShopService } from "../coffeeShop.service";
@graphql.Resolver(() => CoffeeShop)
export class CoffeeShopResolverBase {
  constructor(protected readonly service: CoffeeShopService) {}

  async _coffeeShopsMeta(
    @graphql.Args() args: CoffeeShopCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [CoffeeShop])
  async coffeeShops(
    @graphql.Args() args: CoffeeShopFindManyArgs
  ): Promise<CoffeeShop[]> {
    return this.service.coffeeShops(args);
  }

  @graphql.Query(() => CoffeeShop, { nullable: true })
  async coffeeShop(
    @graphql.Args() args: CoffeeShopFindUniqueArgs
  ): Promise<CoffeeShop | null> {
    const result = await this.service.coffeeShop(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => CoffeeShop)
  async deleteCoffeeShop(
    @graphql.Args() args: DeleteCoffeeShopArgs
  ): Promise<CoffeeShop | null> {
    try {
      return await this.service.deleteCoffeeShop(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
